begin
	insert into dbo.Genres (Name)
	values ('Action'),
	('Adventure'),
	('Cars'),
	('Comedy'),
	('Dementia'),
	('Demons'),
	('Drama'),
	('Ecchi'),
	('Fantasy'),
	('Game'),
	('Harem'),
	('Historical'),
	('Horror'),
	('Josei'),
	('Kids'),
	('Magic'),
	('Martial Arts'),
	('Mecha'),
	('Military'),
	('Music'),
	('Mystery'),
	('Parody'),
	('Police'),
	('Psychological'),
	('Romance'),
	('Samurai'),
	('School'),
	('Sci-Fi'),
	('Seinen'),
	('Shoujo'),
	('Shoujo Ai'),
	('Shounen'),
	('Shounen Ai'),
	('Slice of Life'),
	('Space'),
	('Sports'),
	('Magic'),
	('Super Power'),
	('Supernatural'),
	('Thriller'),
	('Vampire'),
	('Yaoi'),
	('Yuri');
end